# Сегментация изображений. Архитектура U-Net

__Использованные матриалы__

* [U-Net](https://www.machinelearningnuggets.com/image-segmentation-with-u-net-define-u-net-model-from-scratch-in-keras-and-tensorflow/)
* [Kaggle dataset](https://www.kaggle.com/competitions/data-science-bowl-2018/data?ref=machinelearningnuggets.comv)
* [Conv2D](https://keras.io/api/layers/convolution_layers/convolution2d/)
* [Conv2DTranspose](https://keras.io/api/layers/convolution_layers/convolution2d_transpose/)
* [Сoncatenate layer](https://keras.io/api/layers/merging_layers/concatenate/)

In [2]:
import tensorflow as tf
import os
import random
import numpy as np
 
from tqdm import tqdm 

from skimage.io import imread, imshow
from skimage.transform import resize
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'skimage'

## Пример конкатенации двух массивов

In [3]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
x = np.arange(20).reshape(2, 2, 5)
y = np.arange(20, 40).reshape(2, 2, 5)
x_concat_y = tf.keras.layers.Concatenate()([x, y])

x, y, x_concat_y

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]]),
 array([[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],
 
        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]),
 <tf.Tensor: shape=(2, 2, 10), dtype=int64, numpy=
 array([[[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
         [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29]],
 
        [[10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
         [15, 16, 17, 18, 19, 35, 36, 37, 38, 39]]])>)

## Загрузка датасета с Kaggle

In [1]:
seed = 42
np.random.seed = seed

IMG_WIDTH = 128
IMG_HEIGHT = 128
IMG_CHANNELS = 3

TRAIN_PATH = 'data/stage1_train/'
TEST_PATH = 'data/stage1_test/'

train_ids = next(os.walk(TRAIN_PATH))[1]
test_ids = next(os.walk(TEST_PATH))[1]

X = np.zeros((len(train_ids), IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), dtype=np.uint8)
y = np.zeros((len(train_ids), IMG_HEIGHT, IMG_WIDTH, 1), dtype=bool)

NameError: name 'np' is not defined

In [6]:
print('Resizing training images and masks')
for n, id_ in tqdm(enumerate(train_ids), total=len(train_ids)):   
    path = TRAIN_PATH + id_
    img = imread(path + '/images/' + id_ + '.png')[:,:,:IMG_CHANNELS]  
    img = resize(img, (IMG_HEIGHT, IMG_WIDTH), mode='constant', preserve_range=True)
    X[n] = img  #Fill empty X_train with values from img
    mask = np.zeros((IMG_HEIGHT, IMG_WIDTH, 1), dtype=bool)
    for mask_file in next(os.walk(path + '/masks/'))[2]:
        mask_ = imread(path + '/masks/' + mask_file)
        mask_ = np.expand_dims(resize(mask_, (IMG_HEIGHT, IMG_WIDTH), mode='constant',  
                                      preserve_range=True), axis=-1)
        mask = np.maximum(mask, mask_)  
            
    y[n] = mask 

Resizing training images and masks


NameError: name 'train_ids' is not defined